replicaCount: 2
image:
  repository: ikambarov
  name: flaskex
  tag: 0c9b360ff52e839eb03e33f18c6ef2d6323996ae
pod:
  requests:
    cpu: "100m"
  limits:
    cpu: "100m"
  port: 5000
service:
  port: 80
  type: LoadBalancer
hpa:
  max: 10
  min: 2
  cpu_target: 75
  